### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.15.0-91-generic (x86_64)

### ISSUE THREAD

**Issue by maximohneilian** [Plippo/asus-wmi-screenpad#60]
I am having a problem building the module on my Zenbook Pro Duo (UX8402) with Linux Mint and Kernel 5.15.0-91

This is the log:

> DKMS make.log for asus-wmi-1.0 for kernel 5.15.0-91-generic (x86_64)
> Sun Feb 25 04:02:25 PM CET 2024
> make: Entering directory '/usr/src/linux-headers-5.15.0-91-generic'
>   CC [M]  /var/lib/dkms/asus-wmi/1.0/build/asus-wmi.o
>   CC [M]  /var/lib/dkms/asus-wmi/1.0/build/asus-nb-wmi.o
> /var/lib/dkms/asus-wmi/1.0/build/asus-wmi.c: In function ‘asus_wmi_input_init’:
> /var/lib/dkms/asus-wmi/1.0/build/asus-wmi.c:430:47: error: ‘ASUS_WMI_DEVID_LID_FLIP_ROG’ undeclared (first use in this function); did you mean ‘ASUS_WMI_DEVID_LID_FLIP’?
>   430 |                 asus_wmi_tablet_sw_init(asus, ASUS_WMI_DEVID_LID_FLIP_ROG, NOTIFY_LID_FLIP_ROG);
>       |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                               ASUS_WMI_DEVID_LID_FLIP
> /var/lib/dkms/asus-wmi/1.0/build/asus-wmi.c:430:47: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [scripts/Makefile.build:297: /var/lib/dkms/asus-wmi/1.0/build/asus-wmi.o] Error 1
> 
> make: *** [Makefile:1909: /var/lib/dkms/asus-wmi/1.0/build] Error 2
> make: Leaving directory '/usr/src/linux-headers-5.15.0-91-generic'
