### ISSUE TITLE
`dkms build` Error on kernel: 7.0.0-22-generic (x86_64)

### ISSUE THREAD

**Issue by s-light** [Plippo/asus-wmi-screenpad#73]
i just tried to build this for my updated system..
anyone an idea what happend here?

```bash
$ sudo dkms build -m asus-wmi -v 1.0
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Building module(s)...(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=7.0.0-22-generic -C /lib/modules/7.0.0-22-generic/build M=/var/lib/dkms/asus-wmi/1.0/build
ERROR (dkms apport): binary package for asus-wmi: 1.0 not found

Error! Bad return status for module build on kernel: 7.0.0-22-generic (x86_64)
Consult /var/lib/dkms/asus-wmi/1.0/build/make.log for more information.
```

`/var/lib/dkms/asus-wmi/1.0/build/make.log`
```
DKMS (dkms-3.2.2) make.log for asus-wmi/1.0 for kernel 7.0.0-22-generic (x86_64)
Mo 29. Jun 12:06:57 CEST 2026

Building module(s)
# command: make -j16 KERNELRELEASE=7.0.0-22-generic -C /lib/modules/7.0.0-22-generic/build M=/var/lib/dkms/asus-wmi/1.0/build
make: Entering directory '/usr/src/linux-headers-7.0.0-22-generic'
make[1]: Entering directory '/var/lib/dkms/asus-wmi/1.0/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc (Ubuntu 15.2.0-16ubuntu1) 15.2.0
  You are using:           gcc (Ubuntu 15.2.0-16ubuntu1) 15.2.0
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 131
  You are using:             0
  CC [M]  asus-wmi.o
  CC [M]  asus-nb-wmi.o
In file included from /usr/src/linux-headers-7.0.0-22-generic/include/linux/bits.h:30,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/ioport.h:14,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/acpi.h:13,
                 from asus-wmi.c:16:
asus-wmi.c: In function ‘screenpad_led_update’:
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:54: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                                                      ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2032:16: note: in expansion of macro ‘container_of’
 2032 |         asus = container_of(work, struct asus_wmi, screenpad_led_work);
      |                ^~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/compiler_types.h:617:27: error: expression in static assertion is not an integer
  617 | #define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2032:16: note: in expansion of macro ‘container_of’
 2032 |         asus = container_of(work, struct asus_wmi, screenpad_led_work);
      |                ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-7.0.0-22-generic/include/uapi/linux/posix_types.h:5,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/uapi/linux/types.h:14,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/types.h:5,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/kasan-checks.h:5,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/asm-generic/rwonce.h:26,
                 from /usr/src/linux-headers-7.0.0-22-generic/arch/x86/include/generated/asm/rwonce.h:1,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/compiler.h:372,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/cleanup.h:5,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/acpi.h:11:
/usr/src/linux-headers-7.0.0-22-generic/include/linux/stddef.h:16:33: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
   16 | #define offsetof(TYPE, MEMBER)  __builtin_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:24:28: note: in expansion of macro ‘offsetof’
   24 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
asus-wmi.c:2032:16: note: in expansion of macro ‘container_of’
 2032 |         asus = container_of(work, struct asus_wmi, screenpad_led_work);
      |                ^~~~~~~~~~~~
asus-wmi.c:2034:26: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_wk’
 2034 |         ctrl_param = asus->screenpad_led_wk;
      |                          ^~
asus-wmi.c: In function ‘screenpad_led_set’:
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:54: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                                                      ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2052:16: note: in expansion of macro ‘container_of’
 2052 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/compiler_types.h:617:27: error: expression in static assertion is not an integer
  617 | #define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2052:16: note: in expansion of macro ‘container_of’
 2052 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/stddef.h:16:33: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
   16 | #define offsetof(TYPE, MEMBER)  __builtin_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:24:28: note: in expansion of macro ‘offsetof’
   24 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
asus-wmi.c:2052:16: note: in expansion of macro ‘container_of’
 2052 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
asus-wmi.c:2054:13: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_wk’
 2054 |         asus->screenpad_led_wk = value;
      |             ^~
asus-wmi.c:2055:46: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
 2055 |         queue_work(asus->led_workqueue, &asus->screenpad_led_work);
      |                                              ^~
asus-wmi.c: In function ‘screenpad_led_get’:
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:54: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                                                      ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2063:16: note: in expansion of macro ‘container_of’
 2063 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/compiler_types.h:617:27: error: expression in static assertion is not an integer
  617 | #define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/build_bug.h:80:56: note: in definition of macro ‘__static_assert’
   80 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:9: note: in expansion of macro ‘static_assert’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |         ^~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:21:23: note: in expansion of macro ‘__same_type’
   21 |         static_assert(__same_type(*(ptr), ((type *)0)->member) ||       \
      |                       ^~~~~~~~~~~
asus-wmi.c:2063:16: note: in expansion of macro ‘container_of’
 2063 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/stddef.h:16:33: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
   16 | #define offsetof(TYPE, MEMBER)  __builtin_offsetof(TYPE, MEMBER)
      |                                 ^~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/container_of.h:24:28: note: in expansion of macro ‘offsetof’
   24 |         ((type *)(__mptr - offsetof(type, member))); })
      |                            ^~~~~~~~
asus-wmi.c:2063:16: note: in expansion of macro ‘container_of’
 2063 |         asus = container_of(led_cdev, struct asus_wmi, screenpad_led);
      |                ^~~~~~~~~~~~
asus-wmi.c: In function ‘asus_wmi_led_exit’:
asus-wmi.c:2081:38: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2081 |         led_classdev_unregister(&asus->screenpad_led);
      |                                      ^~
asus-wmi.c: In function ‘asus_wmi_led_init’:
asus-wmi.c:2203:21: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_wk’
 2203 |                 asus->screenpad_led_wk = led_val;
      |                     ^~
In file included from /usr/src/linux-headers-7.0.0-22-generic/include/linux/srcu.h:21,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/notifier.h:16,
                 from /usr/src/linux-headers-7.0.0-22-generic/arch/x86/include/asm/uprobes.h:13,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/uprobes.h:66,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/mm_types.h:16,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/mmzone.h:22,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/gfp.h:7,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/slab.h:17,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/resource_ext.h:11,
                 from /usr/src/linux-headers-7.0.0-22-generic/include/linux/acpi.h:14:
asus-wmi.c:2204:32: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                                ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:294:30: note: in definition of macro ‘__INIT_WORK_KEY’
  294 |                 __init_work((_work), _onstack);                         \
      |                              ^~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:309:9: note: in expansion of macro ‘__INIT_WORK’
  309 |         __INIT_WORK((_work), (_func), 0)
      |         ^~~~~~~~~~~
asus-wmi.c:2204:17: note: in expansion of macro ‘INIT_WORK’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                 ^~~~~~~~~
asus-wmi.c:2204:32: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                                ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:295:18: note: in definition of macro ‘__INIT_WORK_KEY’
  295 |                 (_work)->data = (atomic_long_t) WORK_DATA_INIT();       \
      |                  ^~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:309:9: note: in expansion of macro ‘__INIT_WORK’
  309 |         __INIT_WORK((_work), (_func), 0)
      |         ^~~~~~~~~~~
asus-wmi.c:2204:17: note: in expansion of macro ‘INIT_WORK’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                 ^~~~~~~~~
asus-wmi.c:2204:32: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                                ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:296:34: note: in definition of macro ‘__INIT_WORK_KEY’
  296 |                 INIT_LIST_HEAD(&(_work)->entry);                        \
      |                                  ^~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:309:9: note: in expansion of macro ‘__INIT_WORK’
  309 |         __INIT_WORK((_work), (_func), 0)
      |         ^~~~~~~~~~~
asus-wmi.c:2204:17: note: in expansion of macro ‘INIT_WORK’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                 ^~~~~~~~~
asus-wmi.c:2204:32: error: ‘struct asus_wmi’ has no member named ‘screenpad_led_work’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                                ^~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:297:18: note: in definition of macro ‘__INIT_WORK_KEY’
  297 |                 (_work)->func = (_func);                                \
      |                  ^~~~~
/usr/src/linux-headers-7.0.0-22-generic/include/linux/workqueue.h:309:9: note: in expansion of macro ‘__INIT_WORK’
  309 |         __INIT_WORK((_work), (_func), 0)
      |         ^~~~~~~~~~~
asus-wmi.c:2204:17: note: in expansion of macro ‘INIT_WORK’
 2204 |                 INIT_WORK(&asus->screenpad_led_work, screenpad_led_update);
      |                 ^~~~~~~~~
asus-wmi.c:2206:21: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2206 |                 asus->screenpad_led.name = "asus::screenpad";
      |                     ^~
asus-wmi.c:2207:21: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2207 |                 asus->screenpad_led.brightness_set = screenpad_led_set;
      |                     ^~
asus-wmi.c:2208:21: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2208 |                 asus->screenpad_led.brightness_get = screenpad_led_get;
      |                     ^~
asus-wmi.c:2209:21: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2209 |                 asus->screenpad_led.max_brightness = 0xff;
      |                     ^~
asus-wmi.c:2212:49: error: ‘struct asus_wmi’ has no member named ‘screenpad_led’
 2212 |                                            &asus->screenpad_led);
      |                                                 ^~
make[3]: *** [/usr/src/linux-headers-7.0.0-22-generic/scripts/Makefile.build:289: asus-wmi.o] Error 1
make[2]: *** [/usr/src/linux-headers-7.0.0-22-generic/Makefile:2110: .] Error 2
make[1]: *** [/usr/src/linux-headers-7.0.0-22-generic/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/asus-wmi/1.0/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-7.0.0-22-generic'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```
